name = "shiny-dice"
main = "src/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

# Import .wasm files as WebAssembly.Module bindings
[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
